### ISSUE TITLE
Fix broken circle ci pipeline

### ISSUE THREAD

**Issue by munichpavel** [munichpavel/fake-data-for-learning#26]
E.g. https://app.circleci.com/pipelines/github/munichpavel/fake-data-for-learning/150/workflows/068035ce-b027-48b9-ab49-6d1af6c4824b/jobs/152, 

with error message

```console
#!/bin/bash -eo pipefail
sudo apt-get update
sudo apt-get install libglpk-dev
python -m venv env
source env/bin/activate
pip install -r requirements.txt
pip install .

    100% |████████████████████████████████| 286kB 4.9MB/s eta 0:00:01
Collecting pytest-runner (from -r requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/f4/f5/6605d73bf3f4c198915872111b10c4b3c2dccd8485f47b7290ceef037190/pytest_runner-5.3.1-py3-none-any.whl
Collecting nbconvert (from -r requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/13/2f/acbe7006548f3914456ee47f97a2033b1b2f3daf921b12ac94105d87c163/nbconvert-6.0.7-py3-none-any.whl (552kB)
    100% |████████████████████████████████| 552kB 2.4MB/s eta 0:00:01
Collecting bump2version (from bumpversion->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1d/e3/fa60c47d7c344533142eb3af0b73234ef8ea3fb2da742ab976b947e717df/bump2version-1.0.1-py2.py3-none-any.whl
Collecting pytz>=2017.2 (from pandas->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl (503kB)
    100% |████████████████████████████████| 512kB 2.8MB/s eta 0:00:01
Collecting python-dateutil>=2.7.3 (from pandas->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 6.1MB/s eta 0:00:01
Collecting setuptools>=38.4 (from xarray->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/29/e3/a1edb6bef52fd8d4cbe62cf2b6b444e7145edf89fae7ce9bffbfb92ae8b9/setuptools-59.3.0-py3-none-any.whl (952kB)
    100% |████████████████████████████████| 952kB 286kB/s eta 0:00:011
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a0/34/895006117f6fce0b4de045c87e154ee4a20c68ec0a4c9a36d900888fb6bc/pyparsing-3.0.6-py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 13.2MB/s a 0:00:01
Collecting pillow>=6.2.0 (from matplotlib->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7d/2a/2fc11b54e2742db06297f7fa7f420a0e3069fdcf0e4b57dfec33f0b08622/Pillow-8.4.0.tar.gz (49.4MB)
    100% |████████████████████████████████| 49.4MB 28kB/s  eta 0:00:0101
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a7/1b/cbd8ae738719b5f41592a12057ef5442e2ed5f5cb5451f8fc7e9f8875a1a/kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.3MB/s eta 0:00:01
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl
Collecting decorator<5,>=4.3 (from networkx->-r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting cvxopt (from pypoman->-r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/12/ec/fa55aa3638d7ed6c382e30ceea5d688b050d287948234bff214c0d1687f3/cvxopt-1.2.7.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 361kB/s eta 0:00:011
Collecting pycddlib (from pypoman->-r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/8d/b1/5bcf723c08eb1180bb40c753597e6525b90f986ef093ed8e1152887fe1d2/pycddlib-2.1.4.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 5.6MB/s eta 0:00:01
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'Cython' (maybe misspelled?)
    No local packages or working download links found for Cython
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-154rik09/pycddlib/setup.py", line 131, in <module>
        python_requires='>=3.6',
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/circleci/circleci-fake-data/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Cython')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-154rik09/pycddlib/
You are using pip version 9.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Exited with code exit status 1
```

I am using pip v9.0.1 ?!?!?!

**Comment by munichpavel** [comment]
## Fix

I did the following in .circle/config.yml

* upgrade pip before any pip installs
* run tests from same stage as setup (no idea how this worked before--maybe change under the circleci hood?)
* add cython explicitly as dependency (tests pass without this, but shown as an error during dependency installation)
