### ISSUE TITLE
Fix mac os x installation error

### ISSUE THREAD

**Issue by munichpavel** [munichpavel/fake-data-for-learning#36]
As in [this failed ci run](https://github.com/munichpavel/fake-data-for-learning/actions/runs/5737071683/job/15547961291):

```console
Building wheels for collected packages: pycddlib
  Building wheel for pycddlib (setup.py): started
  Building wheel for pycddlib (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-0gex4jnk/pycddlib_edf371a4ee4a4caf81f1a924b7832685/setup.py", line 107, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-0gex4jnk/pycddlib_edf371a4ee4a4caf81f1a924b7832685/.eggs/Cython-3.0.0-py3.11-macosx-10.9-universal2.egg/Cython-3.0.0.dist-info' -> '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-0gex4jnk/pycddlib_edf371a4ee4a4caf81f1a924b7832685/.eggs/Cython-3.0.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycddlib
  Running setup.py clean for pycddlib
  error: subprocess-exited-with-error
```

**Comment by munichpavel** [comment]
Relates to #33 .

## poetry issue

```console
(base) ➜  pauls-ml-playground git:(main) ✗ poetry add fake-data-for-learning
Using version ^0.4.2 for fake-data-for-learning

Updating dependencies
Resolving dependencies... (1.0s)

Writing lock file

Package operations: 3 installs, 1 update, 0 removals

  • Installing cvxopt (1.3.1)
  • Installing pycddlib (2.1.6): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_ext
  warning: cdd.pyx:274:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
  warning: cdd.pyx:275:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
  Compiling cdd.pyx because it changed.
  [1/1] Cythonizing cdd.pyx
  building 'cdd' extension
  creating build
  creating build/temp.macosx-13.0-arm64-cpython-311
  creating build/temp.macosx-13.0-arm64-cpython-311/cddlib
  creating build/temp.macosx-13.0-arm64-cpython-311/cddlib/lib-src
  clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DGMPRATIONAL -Icddlib/lib-src -I/var/folders/4j/sbkhdmj513bdc84vf485j54c0000gn/T/tmpjok19w9j/.venv/include -I/Users/paullarsen/.pyenv/versions/3.11.0/include/python3.11 -c cdd.c -o build/temp.macosx-13.0-arm64-cpython-311/cdd.o
  In file included from cdd.c:1130:
  In file included from cddlib/lib-src/cdd.h:17:
  cddlib/lib-src/cddmp.h:30:11: fatal error: 'gmp.h' file not found
   #include "gmp.h"
            ^~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1


  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pycddlib (2.1.6) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pycddlib (==2.1.6)"'.
```

and [poetry does not support the --use-pep517 flag](https://github.com/python-poetry/poetry/issues/3433).

A work-around was to 

* enter poetry shell `poetry shell`
* pip install using fix of #33, namely `CPPFLAGS="-I$(brew --prefix gmp)/include" LDFLAGS="-L$(brew --prefix gmp)/lib" pip install --use-pep517 pycddlib`
* exit poetry shell
* run `poetry add fake-data-for-learning`.
